name: Build and deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1

      - name: Add Homepage to package.json ğŸ“
        run: |
          sed -i '/"name":/a \  "homepage": "https://ydovzhyk.github.io/BlueHouse/",' package.json

      - name: Set Node Options and Install Dependencies ğŸ“¦
        run: |
          npm ci --legacy-peer-deps

      - name: Build with OpenSSL Compatibility ğŸ› ï¸
        run: |
          NODE_OPTIONS=--openssl-legacy-provider npm run build

      - name: Remove Homepage from package.json ğŸ—‘ï¸
        run: |
          sed -i '/"homepage":/d' package.json

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build
          token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
